# Generated by Django 2.1 on 2019-05-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('father', models.CharField(max_length=20)),
                ('mother', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=100)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassInfo')),
            ],
        ),
    ]
