# Generated by Django 2.1 on 2019-05-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='GuardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(blank=True, max_length=20)),
                ('fmobile', models.CharField(blank=True, max_length=10)),
                ('femail', models.EmailField(default='qaz@gmail.com', max_length=254)),
                ('mother', models.CharField(blank=True, max_length=20)),
                ('mmobile', models.CharField(blank=True, max_length=10)),
                ('memail', models.EmailField(default='cbaaa@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('gender', model_utils.fields.StatusField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, no_check_for_status=True)),
                ('mobile_no', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('photu', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassInfo')),
                ('document', models.ManyToManyField(blank=True, to='students.Document')),
                ('guardian', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.GuardDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
