# Generated by Django 2.1 on 2019-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('totalfees', models.CharField(max_length=6)),
                ('admissionfees', models.CharField(max_length=4)),
                ('monthlyfees', models.CharField(max_length=4)),
                ('ExtraFees', models.CharField(max_length=3)),
                ('strength', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
    ]
