# Generated by Django 2.1 on 2019-06-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190616_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='lassname',
            new_name='classname',
        ),
    ]
