# Generated by Django 2.1 on 2019-06-17 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190616_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 18)),
        ),
    ]
