# Generated by Django 2.2 on 2019-06-22 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190620_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 22)),
        ),
    ]
