# Generated by Django 2.1 on 2019-06-17 19:48

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20190618_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=teachers.models.upload),
        ),
    ]
