# Generated by Django 2.1 on 2019-06-19 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20190618_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duedate',
            field=models.DateField(default=datetime.date(2019, 6, 20)),
        ),
    ]
