# Generated by Django 2.1 on 2019-06-18 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('paidupto', models.CharField(max_length=50)),
                ('paymentdate', models.DateField(default=datetime.date(2019, 6, 18))),
                ('paymentstatus', models.CharField(default='Unsuccessful', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
