# Generated by Django 2.1 on 2019-06-19 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='paidupto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2019, 6, 20)),
        ),
    ]
