# Generated by Django 2.1 on 2019-05-21 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=500)),
                ('attendance_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='update_date')),
                ('mark', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.ClassInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
    ]
